config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  resources :projects do
    resources :notes
    resources :tasks do
      member do
        post :toggle
      end
    end
  end

  namespace :api do
    resources :projects#, only: [:index, :show, :create]
  end

  root "home#index"
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :project
  belongs_to :user

  delegate :name, to: :user, prefix: true

  validates :message, presence: true

  scope :search, ->(term) {
    where("LOWER(message) LIKE ?", "%#{term.downcase}%")
  }

  has_attached_file :attachment

  validates_attachment :attachment,
    content_type: {
      content_type: [
        "image/jpeg",
        "image/gif",
        "image/png",
        "application/pdf",
      ],
    }
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_project
  before_action :project_owner?
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = @project.notes.search(params[:term])
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = @project.notes.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = @project.notes.new(note_params.merge(user: current_user))

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note.project, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note.project, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to @note.project, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:message, :project_id, :attachment)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: [note.project, note], local: true, multipart: true) do |f| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :message %>
    <%= f.text_area :message, class: "form-control", id: :note_message %>
  </div>

  <div class="form-group">
    <%= f.label :attachment %>
    <%= f.file_field :attachment, class: "form-control", id: :note_attachment %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", note.project, class: "btn btn-default", data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div class="note">
  <div class="note-message">
    <%= simple_format note.message %>
  </div>

  <% if note.attachment.exists? %>
    <div class="note-details">
      <span class="glyphicon glyphicon-file"></span>
      <%= link_to note.attachment_file_name, note.attachment.url %>
      (<%= note.attachment_content_type %>,
      <%= number_to_human_size(note.attachment_file_size) %>)
    </div>
  <% end %>

  <h4 class="note-info">
    <%= note.user_name %>,
    <%= full_date(note.created_at) %>
    <%= link_to edit_project_note_path(note.project, note),
        class: "btn btn-default btn-xs btn-inline" do %>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
      Edit
    <% end %>
    <%= link_to [note.project, note], method: :delete,
        data: { confirm: 'Are you sure?' },
        class: "btn btn-default btn-xs" do %>
      <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
      Delete
    <% end %>
  </h4>
</div>

app/views/notes/edit.html.erb
<h1>Edit Note</h1>

<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<h1>Search results for <%= params[:term] %></h1>

<%= render @notes %>

<%= link_to "Back to #{@project.name}", @project, class: "btn btn-primary" %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @note.message %>
</p>

<p>
  <strong>Project:</strong>
  <%= @note.project %>
</p>

<p>
  <strong>User:</strong>
  <%= @note.user %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>