config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  resources :projects do
    resources :notes
    resources :tasks do
      member do
        post :toggle
      end
    end
  end

  namespace :api do
    resources :projects#, only: [:index, :show, :create]
  end

  root "home#index"
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :user_id }

  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  has_many :notes
  has_many :tasks

  def late?
    due_on.in_time_zone < Date.current.in_time_zone
  end
end

app/controllers/api/projects_controller.rb
module Api
  class ProjectsController < ApplicationController

    prepend_before_action :authenticate_user_from_token!

    def index
      @projects = current_user.projects
      render json: @projects
    end

    def show
      @project = Project.find(params[:id])
      render json: @project
    end

    def create
      @project = current_user.projects.new(project_params)

      if @project.save
        render json: { status: :created }
      else
        render json: @project.errors, status: :unprocessable_entity
      end
    end

    private

    def authenticate_user_from_token!
      user_email = params[:user_email].presence
      user = user_email && User.find_by(email: user_email)
      if user && Devise.secure_compare(user.authentication_token, params[:user_token])
        sign_in user, store: true
      else
        render json: { status: "auth failed" }
        false
      end
    end

    def project_params
      params.require(:project).permit(:name, :description, :due_on)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :project_owner?, except: [:index, :new, :create]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :due_on)
    end
end

app/helpers/api/projects_helper.rb
module Api::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control", id: :project_name %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control", id: :project_description %>
  </div>

  <div class="form-group">
    <%= f.label :due_on %>
    <%= f.date_select :due_on, class: "form-control", id: :project_due_on %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
    <% cancel_path = (project.persisted? ? project_path(project) : projects_path) %>
    <%= link_to "Cancel", cancel_path, class: "btn btn-default", data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<h1>
  Projects

  <%= link_to new_project_path, class: "btn btn-primary" do %>
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    New Project
  <% end %>
</h1>


<% @projects.each do |project| %>
  <h2><%= link_to project.name, project %></h2>
  <p>
    <%= project.description %>
  </p>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

app/views/projects/show.html.erb
<h1 class="heading">
  <%= @project.name %>
  <%= link_to edit_project_path(@project), class: "btn btn-default btn-sm btn-inline" do %>
    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
    Edit
  <% end %>
</h1>

<div class="project-description">
  <%= simple_format @project.description %>
</div>

<p>
  Owner:
  <%= @project.owner.name %>
</p>

<p>
  Due: <%= full_date(@project.due_on) %>
</p>

<hr class="divider">

<h2 class="heading">
  Tasks
  <%= link_to new_project_task_path(@project), class: "btn btn-default btn-sm btn-inline" do %>
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
    Add Task
  <% end %>
</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th class="task-actions">Actions</th>
    </tr>
  </thead>

  <tbody>
    <%= render @project.tasks %>
  </tbody>
</table>

<hr class="divider">

<div class="row">
  <div class="col-xs-12 col-md-6">
    <h2 class="heading" style="padding: 0 !important; margin: 0 !important">
      Notes
      <%= link_to new_project_note_path(@project), class: "btn btn-default btn-sm btn-inline" do %>
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        Add Note
      <% end %>
    </h2>
  </div>

  <div class="col-xs-12 col-md-6" style="text-align: right;">
    <%= form_with url: project_notes_path(@project),
        local: true, method: :get, class: "form-inline" do |f| %>
      <div class="form-group has-feedback">
        <%= f.label :term, class: "sr-only" %>
        <%= f.search_field :term, class: "form-control", id: :term, placeholder: "Search Notes" %>
        <i class="glyphicon glyphicon-search form-control-feedback"></i>
        <%= f.submit "Search Notes", class: "btn btn-default sr-only" %>
      </div>
    <% end %>
  </div>
</div>

<%= render @project.notes %>